sudo : required
language: python
services:
  - docker

before_script: pip install docker-compose

script:
  # since there's a dependency on mongo, it will build that image also
  # although we have not added any tests scenario
  - docker-compose run service-2 sh -c "pytest"
